"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
right_format = """$localip $time"""

[character]
success_symbol = "[➜](bold green) " 
error_symbol = "[➜](bold red) " 

[gcloud]
disabled = true

[localip]
ssh_only = false
format = "@[$localipv4](bold red) "
disabled = false

[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "+3"
time_range = "10:00:00-14:00:00"

[battery]
disabled = true
