alias zcfg="vim ~/.zshrc"
alias zrld="source ~/.zshrc"
alias vim="nvim"
alias atlas="NVIM_APPNAME=atlas nvim"
alias python="python3"

alias dev="cd /Users/musyilmaz/Documents/development/"
alias playground="cd /Users/musyilmaz/Documents/development/playground/"
alias urbint="cd /Users/musyilmaz/Documents/development/toptal/urbint/"
alias dotfiles="cd /Users/musyilmaz/Documents/development/dotfiles/"
alias musyilmaz="cd /Users/musyilmaz/Documents/development/musyilmaz.dev/"
